CREATE DATABASE maestro_detalle
GO

USE maestro_detalle
GO

CREATE TABLE VENTAS (
	Id INT NOT NULL IDENTITY (1000, 1),
	Fecha DATETIME NOT NULL,
	Cliente VARCHAR (100) NOT NULL,
	CONSTRAINT PK_VENTAS PRIMARY KEY (Id ASC)
)
GO

CREATE TABLE CONCEPTOS (
	Id INT NOT NULL IDENTITY (10001, 1),
	IdVenta INT NOT NULL,
	Nombre VARCHAR (50) NOT NULL,
	Cantidad INT NOT NULL,
	Precio DECIMAL (18, 2) NOT NULL,
	CONSTRAINT FK_CONCEPTOS_VENTAS FOREIGN KEY (IdVenta) REFERENCES VENTAS (Id)
)
GO
